### ISSUE TITLE
Make 3-column layout responsive

### ISSUE THREAD

**Issue by umatbro** [umatbro/landing-page-1#10]
Obecnie 3-kolumnowy layout wyświetla się identycznie na urządzeniach mobilnych i na desktopach.

Na mobilnych kolumny powinny być ułożone pod sobą (a nie obok siebie).

**Comment by MIachaI** [comment]
Trzeba dodać opcję wrap do v-layout row, wtedy kolumny przy urządzeniach mobilnych schodzą pod siebie. Dodatkowo, żeby to wszystko ładnie się składało, trzeba zmienić styl z margin na padding. Nie wrzucam zmian, bo trzeba wymyślić ostateczny layout strony.

**Comment by umatbro** [comment]
OK

**Comment by MIachaI** [comment]
Wrzuciłem ten commit co miałem, nie ma sensu go kisić. Zmienia układ na trójkolumnowy i ustawia padding zamiast margin [https://github.com/umatbro/landing-page-1/tree/origin/columnLayout](commit)
